In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = "/content/drive/MyDrive/DataMining/"

In [4]:
TourismData2013 = f"{dataset}data_students/TourismData_2013"
TourismData2014 = f"{dataset}data_students/TourismData_2014"
TourismData2015 = f"{dataset}data_students/TourismData_2015"
TourismData2016 = f"{dataset}data_students/TourismData_2016"
TourismData2017 = f"{dataset}data_students/TourismData_2017"
TourismData2018 = f"{dataset}data_students/TourismData_2018"
TourismData2019 = f"{dataset}data_students/TourismData_2019"
TourismData2020 = f"{dataset}data_students/TourismData_2020"
TourismData2021 = f"{dataset}data_students/TourismData_2021"
TourismData2022 = f"{dataset}data_students/TourismData_2022"

In [5]:
NationalityWiseQuarterWiseFTAs2014 = f"{TourismData2014}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2016 = f"{TourismData2016}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2017 = f"{TourismData2017}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2019 = f"{TourismData2019}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2020 = f"{TourismData2020}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2021 = f"{TourismData2021}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"
NationalityWiseQuarterWiseFTAs2022 = f"{TourismData2022}/NATIONALITY-WISE QUARTER-WISE DISTRIBUTION OF FTAs IN INDIA.xlsx"

In [6]:
# data missing for 2013 and 2018
quarterwise_depatures2014 = f"{TourismData2014}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2016 = f"{TourismData2016}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2017 = f"{TourismData2017}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2019 = f"{TourismData2019}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2020 = f"{TourismData2020}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2021 = f"{TourismData2021}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"
quarterwise_depatures2022 = f"{TourismData2022}/QUARTERWISE PERCENTAGE DISTRIBUTION OF DESTINATION COUNTRY WISE DEPARTURES OF INDIAN NATIONALS.xlsx"

## All Years

In [ ]:
dfArrivals2014 = pd.read_excel(NationalityWiseQuarterWiseFTAs2014)
dfArrivals2016 = pd.read_excel(NationalityWiseQuarterWiseFTAs2016)
dfArrivals2017 = pd.read_excel(NationalityWiseQuarterWiseFTAs2017)
dfArrivals2019 = pd.read_excel(NationalityWiseQuarterWiseFTAs2019)
dfArrivals2020 = pd.read_excel(NationalityWiseQuarterWiseFTAs2020)
dfArrivals2021 = pd.read_excel(NationalityWiseQuarterWiseFTAs2021)
dfArrivals2022 = pd.read_excel(NationalityWiseQuarterWiseFTAs2022)

In [ ]:
dfdepatures2014 = pd.read_excel(quarterwise_depatures2014)
dfdepatures2016 = pd.read_excel(quarterwise_depatures2016)
dfdepatures2017 = pd.read_excel(quarterwise_depatures2017)
dfdepatures2019 = pd.read_excel(quarterwise_depatures2019)
dfdepatures2020 = pd.read_excel(quarterwise_depatures2020)
dfdepatures2021 = pd.read_excel(quarterwise_depatures2021)
dfdepatures2022 = pd.read_excel(quarterwise_depatures2022)

In [ ]:
arrivals2014 = dfArrivals2014['Arrivals (in numbers)'].dropna().sum()
arrivals2016 = dfArrivals2016['Arrivals (in numbers)'].dropna().sum()
arrivals2017 = dfArrivals2017['Arrivals (in numbers)'].dropna().sum()
arrivals2019 = dfArrivals2019['Arrivals (in numbers)'].dropna().sum()
arrivals2020 = dfArrivals2020['Arrivals (in numbers)'].dropna().sum()
arrivals2021 = dfArrivals2021['Arrivals (in numbers)'].dropna().sum()
arrivals2022 = dfArrivals2022['Arrivals (in numbers)'].dropna().sum()

In [ ]:
depatures2014 = dfdepatures2014['Departures (In Numbers)'].dropna().sum()
depatures2016 = dfdepatures2016['Departures (In Numbers)'].dropna().sum()
depatures2017 = dfdepatures2017['Departures (In Numbers)'].dropna().sum()
depatures2019 = dfdepatures2019['Departures (In Numbers)'].dropna().sum()
depatures2020 = dfdepatures2020['Departures (In Numbers)'].dropna().sum()
depatures2021 = dfdepatures2021['Departures (In Numbers)'].dropna().sum()
depatures2022 = dfdepatures2022['Departures (In Numbers)'].dropna().sum()

In [ ]:
balances = [arrivals2014 - depatures2014,
              arrivals2016 - depatures2016,
              arrivals2017 - depatures2017,
              arrivals2019 - depatures2019,
              arrivals2020 - depatures2020,
              arrivals2021 - depatures2021,
              arrivals2022 - depatures2022
               ]

In [ ]:
balances

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

years = [2014, 2016, 2017, 2019, 2020, 2021, 2022]
# The years list should have the same number of elements as the differences list.
# Remove the for loop that changes the years list

plt.figure(figsize=(15, 6))
bars = plt.bar(years, balances, color=['green' if diff >=0 else 'red' for diff in balances ])

# Add labels and title
plt.xlabel("Year")
plt.ylabel("Balances in Arrivals")
plt.title("Balances VS Year")


for bar, difference in zip(bars, balances):
    yval = bar.get_height()
    position = yval + 0.1 if difference >= 0 else yval - 0.1
    plt.text(bar.get_x() + bar.get_width()/2, position, round(abs(difference), 2), ha='center', va='bottom' if difference >= 0 else 'top')


plt.show()

## BY CONTINENTS

In [ ]:
continents = ['North America', 'Central & South America', 'Western Europe', 'Eastern Europe', 'Africa', 'West Asia', 'South Asia', 'South East Asia', 'East Asia', 'Australasia']

In [ ]:
continents = [continent.upper() for continent in continents]

In [ ]:
def continent_arrivals_splits_ranges(df):
  indices = []
  index = 0
  for country in df['Country of Nationality']:
    if country.upper() in continents:
      indices.append(index)
    index += 1
  indices.append(len(df['Country of Nationality']))

  ranges = []
  for i in range(len(indices)-1):
      ranges.append([indices[i]+1, indices[i+1]])
  return ranges

In [ ]:
def calcluate_continent_arrivals_split(df, year):
      continent_split = continent_arrivals_splits_ranges(df)
      continentarrivals = []
      #print(f"YEAR : {year}")
      for split, continent in zip(continent_split, continents):
        sum = df.iloc[split[0]:split[1]]['Arrivals (in numbers)'].sum()
        continentarrivals.append(sum)
        #print(f"{continent} : {sum}")
      return continentarrivals

In [ ]:
continentarrivals2014 = calcluate_continent_arrivals_split(dfArrivals2014, 2014)
continentarrivals2016 = calcluate_continent_arrivals_split(dfArrivals2016, 2016)
continentarrivals2017 = calcluate_continent_arrivals_split(dfArrivals2017, 2017)
continentarrivals2019 = calcluate_continent_arrivals_split(dfArrivals2019, 2019)
continentarrivals2020 = calcluate_continent_arrivals_split(dfArrivals2020, 2020)
continentarrivals2021 = calcluate_continent_arrivals_split(dfArrivals2021, 2021)
continentarrivals2022 = calcluate_continent_arrivals_split(dfArrivals2022, 2022)

In [ ]:
def continent_depatures_splits_ranges(df):
  indices = []
  index = 0
  for country in df['Destination Country']:
    if country.upper() in continents:
      indices.append(index)
    index += 1
  indices.append(len(df['Destination Country']))

  ranges = []
  for i in range(len(indices)-1):
      ranges.append([indices[i]+1, indices[i+1]])
  return ranges

In [ ]:
def calcluate_continent_depatures_split(df, year):
      continent_split = continent_depatures_splits_ranges(df)
      #print(f"YEAR : {year}")
      continentdepatures = []
      for split, continent in zip(continent_split, continents):
        sum = df.iloc[split[0]:split[1]]['Departures (In Numbers)'].sum()
        continentdepatures.append(sum)
        #print(f"{continent} : {sum}")
      return continentdepatures

In [ ]:
continentdepatures2014 = calcluate_continent_depatures_split(dfdepatures2014, 2014)
continentdepatures2016 = calcluate_continent_depatures_split(dfdepatures2016, 2016)
continentdepatures2017 = calcluate_continent_depatures_split(dfdepatures2017, 2017)
continentdepatures2019 = calcluate_continent_depatures_split(dfdepatures2019, 2019)
continentdepatures2020 = calcluate_continent_depatures_split(dfdepatures2020, 2020)
continentdepatures2021 = calcluate_continent_depatures_split(dfdepatures2021, 2021)
continentdepatures2022 = calcluate_continent_depatures_split(dfdepatures2022, 2022)

In [ ]:
continentbalances2014 = [continentarrivals2014[i] - continentdepatures2014[i] for i in range(len(continents))]
continentbalances2016 = [continentarrivals2016[i] - continentdepatures2016[i] for i in range(len(continents))]
continentbalances2017 = [continentarrivals2017[i] - continentdepatures2017[i] for i in range(len(continents))]
# 2019 dataset have data fonly 7 continents
#continentbalances2019 = [continentarrivals2019[i] - continentdepatures2019[i] for i in range(len(continentdepatures2019))]
continentbalances2020 = [continentarrivals2020[i] - continentdepatures2020[i] for i in range(len(continents))]
continentbalances2021 = [continentarrivals2021[i] - continentdepatures2021[i] for i in range(len(continents))]
continentbalances2022 = [continentarrivals2022[i] - continentdepatures2022[i] for i in range(len(continents))]

In [ ]:
def plot_balances(continentbalances,year):

    plt.figure(figsize=(15, 6))
    plt.bar(continents, continentbalances, color=['green' if diff >=0 else 'red' for diff in continentbalances])
    plt.xlabel("Continents")
    plt.ylabel("Balances in Arrivals")
    plt.title(f"Balances VS Continents in {year}")
    plt.xticks(rotation=90)
    plt.show()

In [ ]:
# balances are 0 for 2014 because of dataset for depatures and arrivals is same
#plot_balances(continentbalances2014, 2014)

In [ ]:
# plot_balances(continentbalances2016,2016)

In [ ]:
# plot_balances(continentbalances2017,2017)

In [ ]:
# plot_balances(continentbalances2020,2020)

In [ ]:
# plot_balances(continentbalances2021,2021)

In [ ]:
# plot_balances(continentbalances2022,2022)

## TOP 5 CONTINENTS WITH HIGHEST POSITIVE AND NEGATIVE BALANCES

In [ ]:
def top_5_continents(balances, year):
    # Combine continents and balances into a list of tuples
    continent_balance_tuples = list(zip(continents, balances))

    # Sort the tuples by balance in descending order
    sorted_continent_balance_tuples = sorted(continent_balance_tuples, key=lambda x: x[1], reverse=True)

    # Get the top 5 continents with the highest positive balances
    top_5_positive = sorted_continent_balance_tuples[:5]

    # Sort the tuples by balance in ascending order
    sorted_continent_balance_tuples = sorted(continent_balance_tuples, key=lambda x: x[1])

    # Get the top 5 continents with the highest negative balances
    top_5_negative = sorted_continent_balance_tuples[:5]

    print(f"Top 5 Continents with Highest Positive Balances in {year}:")
    for continent, balance in top_5_positive:
        print(f"{continent}: {balance}")

    print(f"\nTop 5 Continents with Highest Negative Balances in {year}:")
    for continent, balance in top_5_negative:
        print(f"{continent}: {balance}")

    return top_5_positive, top_5_negative

In [ ]:
top_5_positive2016, top_5_negative2016 = top_5_continents(continentbalances2016, 2016)

In [ ]:
top_5_negative2017, top_5_positive2017 = top_5_continents(continentbalances2017, 2017)

In [ ]:
top_5_negative2020, top_5_positive2020 = top_5_continents(continentbalances2020, 2020)

In [ ]:
top_5_negative2021, top_5_positive2021 = top_5_continents(continentbalances2021, 2021)

In [ ]:
top_5_negative2022, top_5_positive2022 = top_5_continents(continentbalances2022, 2022)

## COUNTRY WISE

In [ ]:
dfArrivals2014 = pd.read_excel(NationalityWiseQuarterWiseFTAs2014)
dfArrivals2016 = pd.read_excel(NationalityWiseQuarterWiseFTAs2016)
dfArrivals2017 = pd.read_excel(NationalityWiseQuarterWiseFTAs2017)
#dfArrivals2019 = pd.read_excel(NationalityWiseQuarterWiseFTAs2019)
dfArrivals2020 = pd.read_excel(NationalityWiseQuarterWiseFTAs2020)
dfArrivals2021 = pd.read_excel(NationalityWiseQuarterWiseFTAs2021)
dfArrivals2022 = pd.read_excel(NationalityWiseQuarterWiseFTAs2022)

In [ ]:
dfdepatures2014 = pd.read_excel(quarterwise_depatures2014)
dfdepatures2016 = pd.read_excel(quarterwise_depatures2016)
dfdepatures2017 = pd.read_excel(quarterwise_depatures2017)
#dfdepatures2019 = pd.read_excel(quarterwise_depatures2019)
dfdepatures2020 = pd.read_excel(quarterwise_depatures2020)
dfdepatures2021 = pd.read_excel(quarterwise_depatures2021)
dfdepatures2022 = pd.read_excel(quarterwise_depatures2022)

In [ ]:
continents = ['North America', 'Central & South America', 'Western Europe', 'Eastern Europe', 'Africa', 'West Asia', 'South Asia', 'South East Asia', 'East Asia', 'Australasia']

In [ ]:
dfArrivals2014['Country of Nationality'] = dfArrivals2014['Country of Nationality'].str.upper()
dfArrivals2016['Country of Nationality'] = dfArrivals2016['Country of Nationality'].str.upper()
dfArrivals2017['Country of Nationality'] = dfArrivals2017['Country of Nationality'].str.upper()
dfArrivals2020['Country of Nationality'] = dfArrivals2020['Country of Nationality'].str.upper()
dfArrivals2021['Country of Nationality'] = dfArrivals2021['Country of Nationality'].str.upper()
dfArrivals2022['Country of Nationality'] = dfArrivals2022['Country of Nationality'].str.upper()

In [ ]:
dfArrivals2014

In [ ]:
dfdepatures2014['Destination Country'] = dfdepatures2014['Destination Country'].str.upper()
dfdepatures2016['Destination Country'] = dfdepatures2016['Destination Country'].str.upper()
dfdepatures2017['Destination Country'] = dfdepatures2017['Destination Country'].str.upper()
dfdepatures2020['Destination Country'] = dfdepatures2020['Destination Country'].str.upper()
dfdepatures2021['Destination Country'] = dfdepatures2021['Destination Country'].str.upper()
dfdepatures2022['Destination Country'] = dfdepatures2022['Destination Country'].str.upper()

In [ ]:
dfdepatures2020

In [ ]:
def remove_continent_rows_depatures(df):

    # Convert both DataFrame column and continents list to lowercase for comparison
    mask = ~df['Destination Country'].str.upper().isin([c.upper() for c in continents])

    # Apply the mask to filter the DataFrame
    df_filtered = df[mask]

    return df_filtered

In [ ]:
dfdepatures2014 = remove_continent_rows_depatures(dfdepatures2014)
dfdepatures2016 = remove_continent_rows_depatures(dfdepatures2016)
dfdepatures2017 = remove_continent_rows_depatures(dfdepatures2017)
dfdepatures2020 = remove_continent_rows_depatures(dfdepatures2020)
dfdepatures2021 = remove_continent_rows_depatures(dfdepatures2021)
dfdepatures2022 = remove_continent_rows_depatures(dfdepatures2022)

In [ ]:
dfdepatures2020

In [ ]:
def remove_other_rows_depatures(df):
    df = df[df['Destination Country'].str.upper() != 'OTHERS']
    return df

In [ ]:
dfdepatures2014 = remove_other_rows_depatures(dfdepatures2014)
dfdepatures2016 = remove_other_rows_depatures(dfdepatures2016)
dfdepatures2017 = remove_other_rows_depatures(dfdepatures2017)
dfdepatures2020 = remove_other_rows_depatures(dfdepatures2020)
dfdepatures2021 = remove_other_rows_depatures(dfdepatures2021)
dfdepatures2022 = remove_other_rows_depatures(dfdepatures2022)

In [ ]:
dfdepatures2020

In [ ]:
# dfdepatures2014_sorted = dfdepatures2014.sort_values(by='Destination Country')
# dfdepatures2016_sorted = dfdepatures2016.sort_values(by='Destination Country')
# dfdepatures2017_sorted = dfdepatures2017.sort_values(by='Destination Country')
# dfdepatures2020_sorted = dfdepatures2020.sort_values(by='Destination Country')
# dfdepatures2021_sorted = dfdepatures2021.sort_values(by='Destination Country')
# dfdepatures2022_sorted = dfdepatures2022.sort_values(by='Destination Country')

In [ ]:
def remove_continent_rows_arrivals(df):

    # Convert both DataFrame column and continents list to lowercase for comparison
    mask = ~df['Country of Nationality'].str.upper().isin([c.upper() for c in continents])

    # Apply the mask to filter the DataFrame
    df_filtered = df[mask]

    return df_filtered

In [ ]:
dfArrivals2014 = remove_continent_rows_arrivals(dfArrivals2014)
dfArrivals2016 = remove_continent_rows_arrivals(dfArrivals2016)
dfArrivals2017 = remove_continent_rows_arrivals(dfArrivals2017)
dfArrivals2020 = remove_continent_rows_arrivals(dfArrivals2020)
dfArrivals2021 = remove_continent_rows_arrivals(dfArrivals2021)
dfArrivals2022 = remove_continent_rows_arrivals(dfArrivals2022)

In [ ]:
dfArrivals2020

In [ ]:
def remove_other_rows_arrivals(df):
    df = df[df['Country of Nationality'].str.upper() != 'OTHERS']
    return df

In [ ]:
dfArrivals2014 = remove_other_rows_arrivals(dfArrivals2014)
dfArrivals2016 = remove_other_rows_arrivals(dfArrivals2016)
dfArrivals2017 = remove_other_rows_arrivals(dfArrivals2017)
dfArrivals2020 = remove_other_rows_arrivals(dfArrivals2020)
dfArrivals2021 = remove_other_rows_arrivals(dfArrivals2021)
dfArrivals2022 = remove_other_rows_arrivals(dfArrivals2022)

In [ ]:
dfArrivals2020

In [ ]:
arrivals2014_only = set(dfArrivals2014['Country of Nationality']) - set(dfdepatures2014['Destination Country'])
print("Countries 2014 in arrivals but not in departures:", arrivals2014_only)

departures2014_only = set(dfdepatures2014['Destination Country']) - set(dfArrivals2014['Country of Nationality'])
print("\nCountries 2014 in departures but not in arrivals:", departures2014_only)

arrivals2016_only = set(dfArrivals2016['Country of Nationality']) - set(dfdepatures2016['Destination Country'])
print("Countries in arrivals but not in departures:", arrivals2016_only)

depatures2016_only = set(dfdepatures2016['Destination Country']) - set(dfArrivals2016['Country of Nationality'])
print("\nCountries in departures but not in arrivals:", depatures2016_only)

arrivals2017_only = set(dfArrivals2017['Country of Nationality']) - set(dfdepatures2017['Destination Country'])
print("Countries in arrivals but not in departures:", arrivals2017_only)

depatures2017_only = set(dfdepatures2017['Destination Country']) - set(dfArrivals2017['Country of Nationality'])
print("\nCountries in departures but not in arrivals:", depatures2017_only)

arrivals2020_only = set(dfArrivals2020['Country of Nationality']) - set(dfdepatures2020['Destination Country'])
print("Countries in arrivals but not in departures:", arrivals2020_only)

depatures2020_only = set(dfdepatures2020['Destination Country']) - set(dfArrivals2020['Country of Nationality'])
print("\nCountries in departures but not in arrivals:", depatures2020_only)

arrivals2021_only = set(dfArrivals2021['Country of Nationality']) - set(dfdepatures2021['Destination Country'])
print("Countries in arrivals but not in departures:", arrivals2021_only)

depatures2021_only = set(dfdepatures2021['Destination Country']) - set(dfArrivals2021['Country of Nationality'])
print("\nCountries in departures but not in arrivals:", depatures2021_only)

arrivals2022_only = set(dfArrivals2022['Country of Nationality']) - set(dfdepatures2022['Destination Country'])
print("Countries in arrivals but not in departures:", arrivals2022_only)

depatures2022_only = set(dfdepatures2022['Destination Country']) - set(dfArrivals2022['Country of Nationality'])
print("\nCountries in departures but not in arrivals:", depatures2022_only)

In [ ]:
dfdepatures2014_sorted = dfdepatures2014[~dfdepatures2014['Destination Country'].isin(departures2014_only)]
dfdepatures2016_sorted = dfdepatures2016[~dfdepatures2016['Destination Country'].isin(depatures2016_only)]
dfdepatures2017_sorted = dfdepatures2017[~dfdepatures2017['Destination Country'].isin(depatures2017_only)]
dfdepatures2020_sorted = dfdepatures2020[~dfdepatures2020['Destination Country'].isin(depatures2020_only)]
dfdepatures2021_sorted = dfdepatures2021[~dfdepatures2021['Destination Country'].isin(depatures2021_only)]
dfdepatures2022_sorted = dfdepatures2022[~dfdepatures2022['Destination Country'].isin(depatures2022_only)]

In [ ]:
dfdepatures2020_sorted

In [ ]:
dfdepatures2014_sorted = dfdepatures2014_sorted.sort_values(by='Destination Country')
dfdepatures2016_sorted = dfdepatures2016_sorted.sort_values(by='Destination Country')
dfdepatures2017_sorted = dfdepatures2017_sorted.sort_values(by='Destination Country')
dfdepatures2020_sorted = dfdepatures2020_sorted.sort_values(by='Destination Country')
dfdepatures2021_sorted = dfdepatures2021_sorted.sort_values(by='Destination Country')
dfdepatures2022_sorted = dfdepatures2022_sorted.sort_values(by='Destination Country')

In [ ]:
dfdepatures2020_sorted

In [ ]:
dfArrivals2014 = dfArrivals2014[~dfArrivals2014['Country of Nationality'].isin(arrivals2014_only)]
dfArrivals2016 = dfArrivals2016[~dfArrivals2016['Country of Nationality'].isin(arrivals2016_only)]
dfArrivals2017 = dfArrivals2017[~dfArrivals2017['Country of Nationality'].isin(arrivals2017_only)]
dfArrivals2020 = dfArrivals2020[~dfArrivals2020['Country of Nationality'].isin(arrivals2020_only)]
dfArrivals2021 = dfArrivals2021[~dfArrivals2021['Country of Nationality'].isin(arrivals2021_only)]
dfArrivals2022 = dfArrivals2022[~dfArrivals2022['Country of Nationality'].isin(arrivals2022_only)]

In [ ]:
dfArrivals2020

In [ ]:
dfArrivals2014_sorted = dfArrivals2014.sort_values(by='Country of Nationality')
dfArrivals2016_sorted = dfArrivals2016.sort_values(by='Country of Nationality')
dfArrivals2017_sorted = dfArrivals2017.sort_values(by='Country of Nationality')
dfArrivals2020_sorted = dfArrivals2020.sort_values(by='Country of Nationality')
dfArrivals2021_sorted = dfArrivals2021.sort_values(by='Country of Nationality')
dfArrivals2022_sorted = dfArrivals2022.sort_values(by='Country of Nationality')

## TOP 5 POSITIVE BALANCE COUNTRIES

In [ ]:
def top_5_positive_countries(dfArrivals_sorted, dfdepatures_sorted, year):
  print(f"Top 5 Countries with Highest Positive Balances in {year}:")
  countrybalances = dfArrivals_sorted['Arrivals (in numbers)'].values-dfdepatures_sorted['Departures (In Numbers)'].values
  print(dfArrivals_sorted.shape,dfdepatures_sorted.shape,len(countrybalances))
  data = {'Country': dfArrivals_sorted['Country of Nationality'],
          'Balance': countrybalances}

  countrybalances = pd.DataFrame(data)

  # Sort the DataFrame by balance in descending order
  countrybalances_sorted = countrybalances.sort_values(by='Balance', ascending=False)

  # Get the top 5 countries
  top_5_countries = countrybalances_sorted.head(5)

  return top_5_countries

In [ ]:
top_5_positive_countries(dfArrivals2014_sorted, dfdepatures2014_sorted, 2014)

In [ ]:
top_5_positive_countries(dfArrivals2016_sorted, dfdepatures2016_sorted, 2016)

In [ ]:
top_5_positive_countries(dfArrivals2017_sorted, dfdepatures2017_sorted, 2017)

In [ ]:
top_5_positive_countries(dfArrivals2020_sorted, dfdepatures2020_sorted, 2020)

In [ ]:
top_5_positive_countries(dfArrivals2021_sorted, dfdepatures2021_sorted, 2021)

In [ ]:
top_5_positive_countries(dfArrivals2022_sorted, dfdepatures2022_sorted, 2022)

## TOP 5 NEGATIVE BALANCE COUNTRIES

In [ ]:
def top_5_negative_countries(dfArrivals_sorted, dfdepatures_sorted, year):
  print(f"Top 5 Countries with Highest Positive Balances in {year}:")
  countrybalances = dfArrivals_sorted['Arrivals (in numbers)'].values-dfdepatures_sorted['Departures (In Numbers)'].values
  print(dfArrivals_sorted.shape,dfdepatures_sorted.shape,len(countrybalances))
  data = {'Country': dfArrivals_sorted['Country of Nationality'],
          'Balance': countrybalances}

  countrybalances = pd.DataFrame(data)

  # Sort the DataFrame by balance in descending order
  countrybalances_sorted = countrybalances.sort_values(by='Balance', ascending=True)

  # Get the top 5 countries
  top_5_countries = countrybalances_sorted.head(5)

  return top_5_countries

In [ ]:
top_5_negative_countries(dfArrivals2014_sorted, dfdepatures2014_sorted, 2014)

In [ ]:
top_5_negative_countries(dfArrivals2016_sorted, dfdepatures2016_sorted, 2016)

In [ ]:
top_5_negative_countries(dfArrivals2017_sorted, dfdepatures2017_sorted, 2017)

In [ ]:
top_5_negative_countries(dfArrivals2020_sorted, dfdepatures2020_sorted, 2020)

In [ ]:
top_5_negative_countries(dfArrivals2021_sorted, dfdepatures2021_sorted, 2021)

In [ ]:
top_5_negative_countries(dfArrivals2022_sorted, dfdepatures2022_sorted, 2022)